"""Stable foundation API for the elevator access-control simulator."""

from .authorization import authorize
from .clock import Clock, SimulatedClock
from .config import (
    default_config,
    load_config_json,
    load_credentials_json,
    load_startup_json,
)
from .credentials import CredentialRepository
from .controller import Controller
from .event_log import EventLog
from .outputs import OutputManager
from .models import (
    AuthorizationDecision,
    ClockError,
    ConfigurationError,
    ControllerResponse,
    ControllerSnapshot,
    ControllerState,
    CredentialDataError,
    CredentialKey,
    CredentialRecord,
    CredentialRequest,
    DecodedCredential,
    DuplicateCredentialError,
    ElevatorAccessSimError,
    EventDraft,
    EventLogError,
    EventRecord,
    EventType,
    FrameValidation,
    LogAppendOutcome,
    OutputSnapshot,
    ReaderSource,
    Reason,
    RepositoryLookup,
    Result,
    SimulatorConfig,
    StartupData,
    StateInvariantError,
)
from .wiegand import decode_frame, encode_frame, has_valid_parity, validate_frame
from .watchdog import Watchdog

__all__ = [
    "AuthorizationDecision",
    "Clock",
    "ClockError",
    "ConfigurationError",
    "Controller",
    "ControllerResponse",
    "ControllerSnapshot",
    "ControllerState",
    "CredentialDataError",
    "CredentialKey",
    "CredentialRecord",
    "CredentialRepository",
    "CredentialRequest",
    "DecodedCredential",
    "DuplicateCredentialError",
    "ElevatorAccessSimError",
    "EventDraft",
    "EventLogError",
    "EventLog",
    "EventRecord",
    "EventType",
    "FrameValidation",
    "LogAppendOutcome",
    "OutputSnapshot",
    "OutputManager",
    "ReaderSource",
    "Reason",
    "RepositoryLookup",
    "Result",
    "SimulatedClock",
    "SimulatorConfig",
    "StartupData",
    "StateInvariantError",
    "Watchdog",
    "authorize",
    "decode_frame",
    "default_config",
    "encode_frame",
    "has_valid_parity",
    "load_config_json",
    "load_credentials_json",
    "load_startup_json",
    "validate_frame",
]
