"""Stable foundation API for the elevator access-control simulator."""

from .clock import Clock, SimulatedClock
from .config import default_config, load_config_json
from .models import (
    AuthorizationDecision,
    ClockError,
    ConfigurationError,
    ControllerResponse,
    ControllerSnapshot,
    ControllerState,
    CredentialDataError,
    CredentialKey,
    CredentialRecord,
    CredentialRequest,
    DecodedCredential,
    DuplicateCredentialError,
    ElevatorAccessSimError,
    EventDraft,
    EventLogError,
    EventRecord,
    EventType,
    FrameValidation,
    LogAppendOutcome,
    OutputSnapshot,
    ReaderSource,
    Reason,
    RepositoryLookup,
    Result,
    SimulatorConfig,
    StartupData,
    StateInvariantError,
)
from .wiegand import decode_frame, encode_frame, has_valid_parity, validate_frame

__all__ = [
    "AuthorizationDecision",
    "Clock",
    "ClockError",
    "ConfigurationError",
    "ControllerResponse",
    "ControllerSnapshot",
    "ControllerState",
    "CredentialDataError",
    "CredentialKey",
    "CredentialRecord",
    "CredentialRequest",
    "DecodedCredential",
    "DuplicateCredentialError",
    "ElevatorAccessSimError",
    "EventDraft",
    "EventLogError",
    "EventRecord",
    "EventType",
    "FrameValidation",
    "LogAppendOutcome",
    "OutputSnapshot",
    "ReaderSource",
    "Reason",
    "RepositoryLookup",
    "Result",
    "SimulatedClock",
    "SimulatorConfig",
    "StartupData",
    "StateInvariantError",
    "decode_frame",
    "default_config",
    "encode_frame",
    "has_valid_parity",
    "load_config_json",
    "validate_frame",
]
